import { Rubik } from "next/font/google";
import Header from "./(globals)/header";
import "./globals.css";
import { UserProvider } from "./(context)/userContext";
import Footer from "./(globals)/Footer";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
        <body className={rubik.className}>
          <UserProvider>
          <Header />
            <main>
              {children}
            </main>
            <Footer />
          </UserProvider>
        </body>
    </html>
  );
}
