import { Rubik } from "next/font/google";
import Header from "./(globals)/header";
import "./globals.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={rubik.className}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
